"""Add cascade delete to user FKs

Revision ID: a2af59480067
Revises: 5cc6620d7da9
Create Date: 2026-06-13 16:00:17.307047
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = 'a2af59480067'
down_revision = '5cc6620d7da9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analytics_user_id_fkey'), 'analytics', type_='foreignkey')
    op.create_foreign_key(None, 'analytics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('assessment_results_user_id_fkey'), 'assessment_results', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('learner_profiles_user_id_fkey'), 'learner_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'learner_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('learning_paths_user_id_fkey'), 'learning_paths', type_='foreignkey')
    op.create_foreign_key(None, 'learning_paths', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lessons_user_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('mastery_records_user_id_fkey'), 'mastery_records', type_='foreignkey')
    op.create_foreign_key(None, 'mastery_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tutor_conversations_user_id_fkey'), 'tutor_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'tutor_conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutor_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('tutor_conversations_user_id_fkey'), 'tutor_conversations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'mastery_records', type_='foreignkey')
    op.create_foreign_key(op.f('mastery_records_user_id_fkey'), 'mastery_records', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_user_id_fkey'), 'lessons', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'learning_paths', type_='foreignkey')
    op.create_foreign_key(op.f('learning_paths_user_id_fkey'), 'learning_paths', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'learner_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('learner_profiles_user_id_fkey'), 'learner_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_results_user_id_fkey'), 'assessment_results', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.create_foreign_key(op.f('analytics_user_id_fkey'), 'analytics', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

