"""Add cascade delete to tutor messages

Revision ID: ce729028fd24
Revises: a2af59480067
Create Date: 2026-06-14 14:10:25.996428
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = 'ce729028fd24'
down_revision = 'a2af59480067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tutor_messages_conversation_id_fkey'), 'tutor_messages', type_='foreignkey')
    op.create_foreign_key(None, 'tutor_messages', 'tutor_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutor_messages', type_='foreignkey')
    op.create_foreign_key(op.f('tutor_messages_conversation_id_fkey'), 'tutor_messages', 'tutor_conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###

