"use client";

import { useState } from "react";
import Editor from "@monaco-editor/react";
import { Play, EyeOff, Loader2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface CodeBlockProps {
  code: string;
  language?: string;
  output?: string;
}

type OutputState = "hidden" | "running" | "visible";

export default function CodeBlock({ code, language = "python", output }: CodeBlockProps) {
  const [outputState, setOutputState] = useState<OutputState>("hidden");

  const handleToggleOutput = () => {
    if (outputState === "visible") {
      setOutputState("hidden");
    } else if (outputState === "hidden") {
      setOutputState("running");
      // Simulate terminal execution delay
      setTimeout(() => {
        setOutputState("visible");
      }, 800);
    }
  };

  // Catch any over-escaped literal \n characters from the LLM and convert to actual newlines
  let cleanCode = code.replace(/\\n/g, "\n").replace(/\\"/g, '"').trim();

  // Strip markdown code block wrappers generated by the LLM (e.g. ```python \n ... \n ```)
  if (cleanCode.startsWith("```")) {
    const lines = cleanCode.split("\n");
    if (lines.length > 0 && lines[0].startsWith("```")) {
      lines.shift(); // remove opening ```language
    }
    if (lines.length > 0 && lines[lines.length - 1].startsWith("```")) {
      lines.pop(); // remove closing ```
    }
    cleanCode = lines.join("\n").trim();
  }

  const cleanOutput = output ? output.replace(/\\n/g, "\n").replace(/\\"/g, '"') : undefined;

  return (
    <div className="rounded-2xl overflow-hidden border border-white/10 bg-[#0A0A0A] my-6 drop-shadow-xl relative group flex flex-col">
      {/* Header bar */}
      <div className="bg-white/5 border-b border-white/10 px-4 py-3 flex items-center justify-between z-10 relative">
        <div className="flex gap-2 items-center">
          <div className="w-3 h-3 rounded-full bg-rose-500/50" />
          <div className="w-3 h-3 rounded-full bg-amber-500/50" />
          <div className="w-3 h-3 rounded-full bg-emerald-500/50" />
        </div>
        
        <div className="flex items-center gap-4">
          <span className="text-xs font-mono text-zinc-500 uppercase">{language}</span>
          {cleanOutput && (
            <button 
              onClick={handleToggleOutput}
              disabled={outputState === "running"}
              className="flex items-center gap-1.5 px-3 py-1 bg-indigo-500/10 hover:bg-indigo-500/20 disabled:opacity-50 disabled:cursor-not-allowed border border-indigo-500/20 rounded-md text-xs font-medium text-indigo-300 transition-colors w-28 justify-center"
            >
              {outputState === "hidden" && (
                <>
                  <Play className="w-3 h-3" />
                  Run Code
                </>
              )}
              {outputState === "running" && (
                <>
                  <Loader2 className="w-3 h-3 animate-spin" />
                  Running
                </>
              )}
              {outputState === "visible" && (
                <>
                  <EyeOff className="w-3 h-3" />
                  Hide
                </>
              )}
            </button>
          )}
        </div>
      </div>

      {/* Editor */}
      <div className="p-4 bg-[#0A0A0A] z-10 relative">
        <Editor
          height={`${(cleanCode.split("\n").length * 24) + 32}px`}
          language={language}
          theme="vs-dark"
          value={cleanCode}
          options={{
            readOnly: true,
            minimap: { enabled: false },
            scrollBeyondLastLine: false,
            fontSize: 14,
            fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
            lineHeight: 24,
            padding: { top: 16, bottom: 16 },
            overviewRulerLanes: 0,
            hideCursorInOverviewRuler: true,
            scrollbar: { vertical: "hidden", horizontal: "hidden" },
            contextmenu: false,
          }}
        />
      </div>

      {/* Console Output Panel (Animated Reveal) */}
      <AnimatePresence>
        {cleanOutput && outputState === "visible" && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="border-t border-white/10 bg-black/60 font-mono text-sm overflow-hidden z-0 relative"
          >
            <div className="p-4">
              <div className="text-zinc-500 text-xs uppercase tracking-wider mb-2 select-none flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                Terminal Process Completed
              </div>
              <div className="text-emerald-400 whitespace-pre-wrap mt-3">{cleanOutput}</div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
